version: '3.3'
services:
  my-s2d:
    image: lsb8375/my-s2d:latest
    ports:
      - "8008:8000"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"
    command: redis-server --port 6379
    ports:
      - "6322:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
