name: mys2d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - aioredis
  - anyio
  - async-timeout
  - beautifulsoup4
  - blas=1.0=openblas
  - bottleneck
  - brotli-python
  - bs4
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - cryptography
  - deprecated
  - fastapi
  - h11
  - h2
  - hiredis
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - idna
  - libcxx
  - libffi
  - libgfortran5
  - libopenblas
  - llvm-openmp
  - ncurses
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pip
  - pycparser
  - pydantic
  - pyopenssl
  - pysocks
  - python-dateutil
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - readline
  - redis-py
  - requests
  - rfc3986
  - setuptools
  - six
  - sniffio
  - soupsieve
  - sqlite
  - starlette
  - tk
  - typing-extensions
  - tzdata
  - urllib3
  - uvicorn
  - wheel
  - wrapt
  - xz
  - zlib
  - apscheduler
  - pymysql
  - databases
  - pip:
  - pip:
      - databases
      - aiomysql
